template: |
  # Changes

  $CHANGES
categories:
  - title: 'Breaking changes'
    label: 'type: breaking'
  - title: 'New features'
    label: 'type: feature'
  - title: 'Bug fixes'
    label: 'type: bug'
  - title: 'Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
  - title: 'Performance enhancements'
    label: 'type: performance'

exclude-labels:
  - 'skip-changelog'
