name: Push to NuGet

on:
  push:
    branches: [ rel ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core 3.1.6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.106
        
    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish NuGet packages
      uses: actions/upload-artifact@v2-preview
      with:
        name: Packages
        path: '**/*.nupkg'

    - name: Push NuGet packages
      run: dotnet nuget push **/*.nupkg
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --source https://api.nuget.org/v3/index.json
        --no-symbols true

    - uses: aarnott/nbgv@v0.3
      id: nbgv

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.nbgv.outputs.SemVer2 }}
        RELEASE_BRANCHES: .*
